import { prisma } from "@/lib/prisma";

/**
 * Turns an accepted quote into a tracked project.
 *
 * Pulled out of the "Add to Track" action because three things now do it: that
 * button, answering "we got it" on the quotes list, and a client signing the
 * quote on its public page. Three copies of a transaction that creates a
 * project, its deliverables and its first diary entry is three places for them
 * to drift apart.
 *
 * Returns the existing project when there already is one, so it can be called
 * twice without producing two projects for one quote. That matters most for
 * signing: a client can open the page again and the freelancer can also press
 * the button, and neither should double up.
 */
export async function createProjectFromBrief(
  briefId: string,
  userId: string
): Promise<string> {
  const existing = await prisma.project.findFirst({
    where: { briefId },
    select: { id: true },
  });
  if (existing) return existing.id;

  const brief = await prisma.brief.findUnique({ where: { id: briefId } });
  if (!brief) throw new Error("Brief not found.");

  const deliverables = (brief.deliverables as string[]).map((name, order) => ({ name, order }));

  const project = await prisma.$transaction(async (tx) => {
    const created = await tx.project.create({
      data: {
        userId,
        briefId: brief.id,
        title: brief.title,
        client: brief.client,
        price: brief.price,
        hours: brief.hours,
        timeline: brief.timeline,
        currency: brief.currency,
        deliverables: { create: deliverables },
      },
    });
    await tx.diaryEntry.create({
      data: {
        projectId: created.id,
        title: "Project kicked off",
        // The plan, and nothing in front of it.
        body: brief.timeline || "",
        autoGenerated: true,
      },
    });
    await tx.brief.update({ where: { id: brief.id }, data: { status: "TRACKED" } });
    return created;
  });

  return project.id;
}
