import { prisma } from "@/lib/prisma";

/**
 * Turns an accepted quote into a tracked project.
 *
 * Pulled out of the "Add to Track" action because three things now do it: that
 * button, answering "we got it" on the quotes list, and a client signing the
 * quote on its public page. Three copies of a transaction that creates a
 * project, its deliverables and its first diary entry is three places for them
 * to drift apart.
 *
 * Returns the existing project when there already is one, so it can be called
 * twice without producing two projects for one quote. That matters most for
 * signing: a client can open the page again and the freelancer can also press
 * the button, and neither should double up.
 */
export async function createProjectFromBrief(
  briefId: string,
  userId: string
): Promise<string> {
  const existing = await prisma.project.findFirst({
    where: { briefId },
    select: { id: true },
  });
  if (existing) return existing.id;

  const brief = await prisma.brief.findUnique({ where: { id: briefId } });
  if (!brief) throw new Error("Brief not found.");

  const names = brief.deliverables as string[];
  const deliverables = names.map((name, order) => ({ name, order }));

  // The milestones the client agreed to, stored on the quote when it was
  // generated. Read back rather than recomputed: this is what was signed, and
  // working it out again from the deliverables could produce a different split
  // from the one on the document.
  const settings = (brief.settings ?? {}) as {
    useMilestones?: boolean;
    milestones?: {
      name: string;
      deliverableIndexes: number[];
      gate?: string;
      amount: number;
    }[];
  };
  const quoted = settings.useMilestones ? settings.milestones ?? [] : [];

  const project = await prisma.$transaction(async (tx) => {
    const created = await tx.project.create({
      data: {
        userId,
        briefId: brief.id,
        title: brief.title,
        client: brief.client,
        price: brief.price,
        hours: brief.hours,
        timeline: brief.timeline,
        currency: brief.currency,
        // A project with milestones bills per milestone, by definition. This
        // is the one place the two facts are set together, so they cannot
        // disagree.
        ...(quoted.length ? { billing: "PER_MILESTONE" as const } : {}),
        deliverables: { create: deliverables },
      },
    });

    // Milestones after the deliverables exist, so each can be pointed at the
    // rows it covers. The quote stored positions in the deliverables list, and
    // those rows were created from the same list in the same order.
    if (quoted.length) {
      const rows = await tx.deliverable.findMany({
        where: { projectId: created.id },
        select: { id: true, order: true },
        orderBy: { order: "asc" },
      });
      const byOrder = new Map(rows.map((r) => [r.order, r.id]));

      // An index loop rather than .entries(): spreading or destructuring an
      // iterator needs a newer compile target than this project uses.
      for (let order = 0; order < quoted.length; order++) {
        const ms = quoted[order];
        const milestone = await tx.milestone.create({
          data: {
            projectId: created.id,
            name: ms.name,
            order,
            amount: ms.amount,
            // The generated client here predates this column; see lib/track-db
            // for the same situation.
            ...({ gate: ms.gate ?? null } as Record<string, unknown>),
          },
        });
        const ids = ms.deliverableIndexes
          .map((i: number) => byOrder.get(i))
          .filter((id: string | undefined): id is string => Boolean(id));
        if (ids.length) {
          await tx.deliverable.updateMany({
            where: { id: { in: ids } },
            data: { milestoneId: milestone.id },
          });
        }
      }
    }
    await tx.diaryEntry.create({
      data: {
        projectId: created.id,
        title: "Project kicked off",
        // The plan, and nothing in front of it.
        body: brief.timeline || "",
        autoGenerated: true,
      },
    });
    await tx.brief.update({ where: { id: brief.id }, data: { status: "TRACKED" } });
    return created;
  });

  return project.id;
}
